package jFrontd.UI;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import jFrontd.Classes.Emulator;
import javax.swing.*;
import java.io.*;
/*
 * EmulatorAdd.java
 *
 * Created on May 12, 2009, 2:27:55 PM
 */

/**
 *
 * @author sj
 */
public class EmulatorAddWindow extends javax.swing.JDialog {

    /** Creates new form EmulatorAdd */
    public EmulatorAddWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private boolean PathExists(){
        File path = new File(txtPath.getText());
        if(!path.exists()){
            JOptionPane.showMessageDialog(null, "Emulator does not exist",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        lblPath = new javax.swing.JLabel();
        lblTypes = new javax.swing.JLabel();
        lblArgs = new javax.swing.JLabel();
        btnPath = new javax.swing.JButton();
        txtDescription = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtArgs = new javax.swing.JTextField();
        txtTypes = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        txtPath = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Emulator...");

        lblName.setText("Name");

        lblDescription.setText("Description");

        lblPath.setText("Path");

        lblTypes.setText("File Types");

        lblArgs.setText("Arguments");

        btnPath.setText("Browse...");
        btnPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPathActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPath)
                            .addComponent(lblDescription)
                            .addComponent(lblName)
                            .addComponent(lblArgs)
                            .addComponent(lblTypes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtPath, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPath))
                            .addComponent(txtArgs, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                            .addComponent(txtDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                            .addComponent(txtTypes, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblArgs, lblDescription, lblName, lblPath, lblTypes});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescription)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPath)
                    .addComponent(btnPath)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTypes)
                    .addComponent(txtTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArgs)
                    .addComponent(txtArgs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblName, txtName});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblDescription, txtDescription});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnPath, lblPath});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblTypes, txtTypes});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblArgs, txtArgs});

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-446)/2, (screenSize.height-222)/2, 446, 222);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        //close me
        this.dispose();
}//GEN-LAST:event_btnCancelActionPerformed

    private void btnPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPathActionPerformed
        //Make a File Chooser window
        JFileChooser fc = new JFileChooser();
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File tempfile = fc.getSelectedFile();
            //set the path to the executable
            txtPath.setText(tempfile.getPath());
        }
    }//GEN-LAST:event_btnPathActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
    //make sure that the fields are filled in
    if(txtName.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Please enter a name for the Emulator.",
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if(txtPath.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Please enter a path for the Emulator.",
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if(txtDescription.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Please enter a Description for the Emulator.",
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if(txtTypes.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, 
                "Please enter supported filetypes for the Emulator, separated by commas.",
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    File path = new File(txtPath.getText());
    if(!path.exists()){
        JOptionPane.showMessageDialog(null, "Emulator does not exist",
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }


    //get the information
    String Name, Description, Path, Types, Args;
    Name = txtName.getText();
    Description = txtDescription.getText();
    Path = txtPath.getText();
    Types = txtTypes.getText();
    Args = txtArgs.getText();
        //create a new emulator
        Emulator myemulator = new Emulator(Name, Path, Description, Args, Types);
    //close the form
    this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnPath;
    private javax.swing.JLabel lblArgs;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPath;
    private javax.swing.JLabel lblTypes;
    private javax.swing.JTextField txtArgs;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPath;
    private javax.swing.JTextField txtTypes;
    // End of variables declaration//GEN-END:variables
    private final String separator = new String(System.getProperty("file.separator"));
    private final String home = new String(System.getProperty("user.home"));
    private final File ConfigDir = new File(home+separator+".jFrontd");
    private final File FolderDir = new File(ConfigDir+separator+"Folders");
    private final File EmulatorDir = new File(ConfigDir+separator+"Emulators");
}
